### ISSUE TITLE
Change the look of footer

### ISSUE THREAD

**Issue by Bhola-B2C** [Bhola-B2C/Aavishkar-2.0-Landing#2]
The footer has couple of texts(Aavishkar 2.0)(Welcome to the next level). Improve the look of same.
Add blink js in 2nd footer. Creativity required.

**Comment by hiteshpr** [comment]
Hi, can I work on this issue?

**Comment by Bhola-B2C** [comment]
Go Ahead

**Comment by hiteshpr** [comment]
Can you elaborate what exactly is needed?

**Comment by Bhola-B2C** [comment]
Sorry, the issue has been solved. Thanks for your interests. 😃
